### ISSUE TITLE
Update  ParallelRunner for Behat 3?

### ISSUE THREAD

**Issue by edysanchez** [shvetsgroup/ParallelRunner#26]
Hello:
Actually I am using behat 3, and I need to parallelize the tests runs.
There is any plan for update for behat 3?
Thx

**Comment by ihorbovkit** [comment]
Hi Guys, any updates how to run parallel test on Behat 3? Thanks

**Comment by kandelyabre** [comment]
try to use https://packagist.org/packages/tonicforhealth/behat-parallel-scenario (the main idea based on this repo)
