### ISSUE TITLE
PHP Version question

### ISSUE THREAD

**Issue by jgonyea** [shvetsgroup/ParallelRunner#30]
Our production, test, and dev environments are all running Centos 6.6, which by default has PHP 5.3.3.  Is there anything specific about PHP 5.3.6 that this package requires?  If not, would you consider lowering the minimum to 5.3.3?

Thanks in advance either way.

bash-4.1# composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for shvetsgroup/parallelrunner dev-master -> satisfiable by shvetsgroup/parallelrunner[dev-master].
    - shvetsgroup/parallelrunner dev-master requires php >=5.3.6 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.

**Comment by grke** [comment]
What does this project provide that cannot be done with 'xargs -P'?

**Comment by jgonyea** [comment]
I'm not familiar with that command.  What does xargs -P do?

**Comment by grke** [comment]
It runs parallel processes. For example:

find -name '*.feature' | xargs -P 4 -n 1 behat_runner.sh

This will run a behat_runner.sh shell script for every feature file that find finds, with a maximum of 4 in parallel. Each instance has a feature file name passed as the first argument.

**Comment by jgonyea** [comment]
If I understand the project correctly, I think that your xargs example would only run feature files in parallel, not scenarios, as this project does.

**Comment by fesor** [comment]
@jgonyea this project doesn't run scenarios in parallel, only features.

I thought about possibility to schedule scenario execution across different workers but found that this doesn't have any performance benefits but complexity of this solution is very high.
